### ISSUE TITLE
Rancher - Account (User)

### ISSUE THREAD

**Issue by dbones** [dbones-labs/lab-dev#16]
Rancher uses are automatically added via the github integration

we will need a away to query for them though

**Comment by dbones** [comment]
```yaml
apiVersion: management.cattle.io/v3
description: ""
displayName: Dave R.
kind: User
metadata:
  annotations:
    authz.management.cattle.io/creator-role-bindings: '{"created":["user"],"required":["user"]}'
    lifecycle.cattle.io/create.mgmt-auth-users-controller: "true"
  finalizers:
  - controller.cattle.io/mgmt-auth-users-controller
  labels:
    CTKN8Q3LC9FNASR5E8T2UBPH70PJGD1P: hashed-principal-name
  name: u-whzq6t3pkh
principalIds:
- github_user://183822
- local://u-whzq6t3pkh
```

note that the principal is not in the spec or status
