### ISSUE TITLE
Kubernetes cluster

### ISSUE THREAD

**Issue by dbones** [dbones-labs/lab-dev#18]
support for adding a k8s cluster into a zone

- local need to just be added
- able to add other clusters which have been registered already
- add cluster labels

**Comment by dbones** [comment]
we need to query for this.

```yaml
apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    objectset.rio.cattle.io/owner-name: dev-eu-01
    objectset.rio.cattle.io/owner-namespace: fleet-default

  labels:
    lab.dev/cloud: on-prem       # add a number of labels for fleet.
    lab.dev/cluster: downstream
    lab.dev/environment: development
    lab.dev/region: eu
    objectset.rio.cattle.io/hash: 384bbf9d46e2027db8bf8fd4bf5a50c3ce2bee8c
    provider.cattle.io: k3s
  name: c-m-ptwk8q76
spec:
  displayName: dev-eu-01
  fleetWorkspaceName: fleet-default

```



LOCAL this cluster is just build different :)


```yaml
apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    authz.management.cattle.io/creator-role-bindings: '{"created":[],"required":["cluster-owner"]}'
    lifecycle.cattle.io/create.cluster-agent-controller-cleanup: "true"
    lifecycle.cattle.io/create.cluster-provisioner-controller: "true"
    lifecycle.cattle.io/create.cluster-scoped-gc: "true"
    lifecycle.cattle.io/create.mgmt-cluster-rbac-remove: "true"
    provisioner.cattle.io/encrypt-migrated: "true"
    provisioner.cattle.io/ke-driver-update: updated
  creationTimestamp: "2022-07-18T02:56:44Z"
  finalizers:
  - controller.cattle.io/cluster-agent-controller-cleanup
  - controller.cattle.io/cluster-scoped-gc
  - controller.cattle.io/cluster-provisioner-controller
  - controller.cattle.io/mgmt-cluster-rbac-remove
  - wrangler.cattle.io/mgmt-cluster-remove
  generation: 50
  labels:
    provider.cattle.io: k3s
  name: local
spec:
  agentImageOverride: ""
  answers: {}
  description: ""
  desiredAgentImage: ""
  desiredAuthImage: ""
  displayName: local
  dockerRootDir: /var/lib/docker
  enableClusterAlerting: false
  enableClusterMonitoring: false
  enableNetworkPolicy: null
  fleetWorkspaceName: fleet-local
  internal: true
  k3sConfig:
    k3supgradeStrategy:
      serverConcurrency: 1
      workerConcurrency: 1
    kubernetesVersion: v1.21.7+k3s1
  localClusterAuthEndpoint:
    enabled: false
  windowsPreferedCluster: false
```
