### ISSUE TITLE
Kubernetes - FF (project)

### ISSUE THREAD

**Issue by dbones** [dbones-labs/lab-dev#2]
when we have a Firefigher raised 

- https://github.com/dbones-labs/lab-dev/blob/main/src/Dev/v1/Core/Tenancies/FireFighter.cs#L9
- https://github.com/dbones-labs/lab-dev/tree/main/src/Dev/Controllers/Github/FireFighting

this needs to be pushed into the the Projects into the downstream streams

using github teams takes time (as the membership/teams needs to be sync'ed) - by default is `0 0 * * *` (once a day)

**Comment by dbones** [comment]
![Image](https://user-images.githubusercontent.com/183849/180918829-eed3f115-78d1-473d-b87e-a0617486cf23.png)



![Image](https://user-images.githubusercontent.com/183849/180918787-7903eacd-e744-406d-8d02-0fa806438775.png)

**Comment by dbones** [comment]
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    p-rksrc_prtb-plwzj: prtb-in-cluster-binding-owner
  name: p-rksrc-prtb-plwzj-project-member
  namespace: c-m-nqtgmjvn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-member
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: u-whzq6t3pkh
```

this looks to be the main thing

we need to add it to the ns of the cluster :)
