### ISSUE TITLE
tenancy and deployment for downstream clusters

### ISSUE THREAD

**Issue by dbones** [dbones-labs/lab-dev#4]
deployment rbac

----
### Rancher require
namespaces to have an annotation 

then rancher can manage the rbac in the project for all the namespaces.

---

### fleet requires (for a secure setup)
- service account
- roles and bindings

to limit where a tenancy can deploy too

serviceaccounts are not linked to projects

so the contecpt of a  `tenancy` will need to be controlled by namepaces, not by projects for this part
---

**Comment by dbones** [comment]
we can setup a separate Repo that is controlled by `lab.dev`, it has all the metadata, this can then be registered with all clusters and push the correct updates (via fleet)

`lab.dev` can checkin changes
- role
- bindings
- service accounts
- namespaces

this would minimise the 
- secrets of downstream clusters being shared (allow fleet to do it)
- informtion we would duplicate if we did a operator in the clusters (again fleet can deploy these items)

however we need to handle git and also have a dedicated Repo, created when the org is setup in Github.

- https://github.com/libgit2/libgit2sharp
- https://stackoverflow.com/questions/54877996/how-to-clone-a-repo-using-libgit2sharp

**Comment by dbones** [comment]
the service account needs alot of access to  default


![Image](https://user-images.githubusercontent.com/183849/181234943-5e31d3c5-71aa-4e4f-9191-29110a147166.png)

**Comment by dbones** [comment]
consider a controller to ensure the resources are correct for each tennet

**Comment by dbones** [comment]
```yaml
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: lab-ds
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: github-credentials
  insecureSkipTLSVerify: false
  paths: []
  repo: https://github.com/fox-in-the-lab/lab.git
  serviceAccount: tenancy1
  targets:
  - clusterGroup: downstream

---

apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: downstream
  namespace: fleet-default
spec:
  selector:
    matchExpressions: []
    matchLabels: {}
 ```

**Comment by dbones** [comment]
![Image](https://user-images.githubusercontent.com/183849/194158711-7f60ddc0-230e-415f-8c82-d6beb200a208.png)

**Comment by dbones** [comment]
use special folders to control deployment to sub-cluster assets



![Image](https://user-images.githubusercontent.com/183849/195240400-2db42741-86ca-4e30-9759-e9610cc37483.png)


```yaml
targetCustomizations:
  - name: bob
    clusterSelector:
      matchExpressions:
        - key: lab.dev/name2
          Operator: In
          values:
            - aqua
    yaml:
      overlays:
        - deploy
```
