### ISSUE TITLE
Github - Tenancy members (team members)

### ISSUE THREAD

**Issue by dbones** [dbones-labs/lab-dev#9]
```yaml
apiVersion: lab.dev/v1
kind: Member
metadata:
  name: dbones
  namespace: galaxy
  labels:
    lab.dev/verison: 1
spec:
  tenancy: platform
  user: dbones
  role: owner # member, owner, guest
```
